version: '3.4'
services:
    sem04:
      image: ${DOCKER_REGISTRY-}sem04
      container_name: students.app
      build:
        context: .
        dockerfile: Dockerfile
    students.db:
      image: mysql:latest
      container_name: students.db
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=studentsDB
      volumes:
        - ./.containers/database:/var/lib/mysql
      ports:
        - "3306:3306"